name: 'Terraform Format, Validate, and Lint'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: 'Terraform Format, Validate, and Lint'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-kubiya-flow

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.0.0"

    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Terraform Format
      run: |
        terraform fmt -check
        echo "fmt_status=$?" >> $GITHUB_ENV
      continue-on-error: true

    - name: Terraform Init
      run: |
        terraform init
        echo "init_status=$?" >> $GITHUB_ENV
      continue-on-error: true

    - name: Terraform Validate
      run: |
        terraform validate
        echo "validate_status=$?" >> $GITHUB_ENV
      continue-on-error: true

    - name: TFLint
      run: |
        tflint --format=compact
        echo "tflint_status=$?" >> $GITHUB_ENV
      continue-on-error: true

    - name: Terraform Check
      if: env.fmt_status == '1' || env.init_status == '1' || env.validate_status == '1' || env.tflint_status == '1'
      run: |
        echo "Terraform format check failed. Please run 'terraform fmt' to fix formatting issues."
        echo "Terraform init failed. Please check the initialization errors."
        echo "Terraform validate failed. Please check the validation errors."
        echo "TFLint found issues. Please check the linting errors."
        exit 1 