tools:
- name: argo-diff-tool
  image: argoproj/argocd
  description: "Get a diff between a live argocd state and a specified revision."
  type: docker
  alias: argocd-differ
  content: |
    # Login first
    argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD  --insecure  --plaintext > /dev/null
    # Get Diff
    app_name="{{ .app_name }}"
    revision="{{ .revision }}"
    if [ -z "$revision" ]; then
        argocd app diff "$app_name"
    else
        argocd app diff $app_name --revision $revision
    fi
    return 0
  args:
    app_name:
      description: 'The app name to compare the revision against on ArgoCD - use the default value if not provided'
      required: false
      default: "koss110-client"
    revision:
      description: 'The revision to compare the app against - use the default value if not provided'
      required: false
      default: "main"
  env:
    - "ARGOCD_SERVER"
    - "ARGOCD_USERNAME"
    - "ARGOCD_PASSWORD"
