name: Terraform CI/CD

on:
  push:
    branches:
      - '**'
jobs:
  terraform:
    name: Plan and Apply on Changed Terraform Module
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::564407622114:role/github-action-role

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          json: true
          dir_names: true
          dir_names_max_depth: 1
          files_ignore: |
            {.github,.git}/**
            
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_modified_files }}'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Plan and Apply Terraform
        if: steps.changed-files.outputs.all_modified_files != ''
        run: |
          IFS=$'\n' read -d '' -r -a dirs < <(echo '${{ steps.changed-files.outputs.all_modified_files }}' | jq -r '.[]')
          for dir in "${dirs[@]}"
          do
            echo "Running Terraform in directory $dir"
            cd $dir
            terraform init
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
            cd -
          done
