name: Terraform CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  terraform:
    name: Plan and Apply on Changed Terraform Module
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::564407622114:role/github-action-role

      - name: Detect Changed Directories
        id: changes
        run: |
          echo "Fetching list of changed files..."
          changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo "Changed files: $changed_files"
          
          changed_dirs=$(echo "$changed_files" | grep 'terraform/' | awk 'BEGIN {FS="/"} {print $1"/"$2}' | uniq)
          echo "Changed directories: $changed_dirs"
          echo "::set-output name=dir::$(echo $changed_dirs)"

      - name: Plan and Apply Terraform
        if: steps.changes.outputs.dir != ''
        run: |
          for dir in ${{ steps.changes.outputs.dir }}
          do
            echo "Running Terraform in directory $dir"
            cd $dir
            terraform init
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
            cd -
          done
